[workspace]
members = [
    "./crates/playing-card",
    "./crates/career-poker",
]
exclude = [
    "./crates/runtime",
    "./crates/plugin-bindings",
    "./crates/example-protocol",
    "./crates/example-plugin"
]
