[workspace]
members = [
    "./crates/cdfy-binding-gen",
    "./crates/cdfy-sdk",
    "./crates/cdfy-sdk-support",
    "./crates/cdfy-runtime",
    "./crates/cdfy-websocket-server"
]
exclude = [
    "./plugins"
]
