version: '3'
services:
  minio:
    image: minio/minio
    command: -c "/usr/bin/minio server --console-address :9090 /data"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    entrypoint: sh
    volumes:
      - ./data/minio:/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cdfy_room_server_dev
    ports:
      - 5434:5432
volumes:
  minio: