set dotenv-load
project := env_var('PROJECT_ID')

run:
    deno run -A --location http://localhost:8080 ./src/server.ts 

test:
    deno run -A ./src/redis.ts

deploy:
    #!/bin/zsh
    deployctl deploy --prod --project={{project}} ./src/server.ts

supabase:
    deno run -A --location http://localhost:8080 ./examples/supabase.ts