[package]
name = "cdfy-server-sdk-mock"
version = "0.1.0"
edition = "2021"

[dependencies]
cdfy-server-sdk = { path = "../cdfy-server-sdk" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rand = "0.8.5"
