[package]
name = "cdfy-binding-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
fp-bindgen = { version = "3.0.0", features = [
  "generators",
]}
once_cell = "1.17.0"
anyhow = "1"
serde = "1.0"
serde_json = "1.0.93"