[package]
name = "cdfy-binding-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
fp-bindgen = { git = "https://github.com/fiberplane/fp-bindgen", features = ["generators"] }
once_cell = "1.17.0"
anyhow = "1"